CREATE TABLE USERS(
        USER_ID VARCHAR(20) NOT NULL,
        EMAIL VARCHAR2(128) NOT NULL,
        PASSWORD VARCHAR2(30) NOT NULL,
        USER_NAME VARCHAR2(128) NOT NULL,
        ADDRESS VARCHAR2(128),
        PHONE_NUMBER VARCHAR2(20),
        ROLE CHAR(1) DEFAULT 'U' NOT NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS_ PRIMARY KEY (USER_ID);

CREATE TABLE BOARD(
    BOARD_ID NUMBER,
    TITLE VARCHAR2(128) NOT NULL,
    CONTENT VARCHAR2(255) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE,
    USER_ID VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(15) DEFAULT '처리중' NOT NULL
);

CREATE SEQUENCE SEQ_BOARD_PK
    START WITH 1
    INCREMENT BY 1;
    
CREATE TABLE COMMENTS(
    COMMENT_ID NUMBER(5) NOT NULL,
    BOARD_ID NUMBER NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    COM_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_COMMENTS_PK
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE ORDERS(
    ORDER_ID VARCHAR2(30) NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    ALBUM_ID VARCHAR2(10) NOT NULL,
    ORDER_DATE DATE,
    TOTAL NUMBER(8),                              
    O_QUANTITY NUMBER(20)
);

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDER_ID PRIMARY KEY (ORDER_ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_USER_ID_ORDERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ALBUM_ID_ORDERS FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID);

CREATE TABLE PHOTO(
    PHOTO_ID VARCHAR2(5) NOT NULL,
    ORDER_ID VARCHAR2(30) NOT NULL,
    PHOTO_NAME VARCHAR2(128) NOT NULL
);

ALTER TABLE PHOTO ADD CONSTRAINT PK_PHOTO_ID PRIMARY KEY (PHOTO_ID);
ALTER TABLE PHOTO ADD CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

CREATE TABLE ALBUM(
    ALBUM_ID VARCHAR2(10) NOT NULL,
    MATERIAL VARCHAR2(50) NOT NULL, --LINEN / LEATHER / HARD / SOFT
    COLOR VARCHAR2(50) NOT NULL, -- GRAY / BLUE / BROWN
    ALBUM_SIZE CHAR(1) NOT NULL  -- S M B
);

ALTER TABLE ALBUM ADD CONSTRAINT PK_ALBUM_ID PRIMARY KEY (ALBUM_ID);

INSERT INTO ALBUM (ALBUM_ID, MATERIAL, COLOR, ALBUM_SIZE)
    SELECT 'A001' , 'LINEN' , 'GRAY' , 'S'  FROM DUAL
    UNION ALL
    SELECT 'A002' , 'LINEN' , 'BLUE' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A003' , 'LINEN' , 'BROWN' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A004' , 'LINEN' , 'GRAY' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A005' , 'LINEN' , 'BLUE' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A006' , 'LINEN' , 'BROWN' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A007' , 'LEATHER' , 'GRAY' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A008' , 'LEATHER' , 'BROWN' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A009' , 'LEATHER' , 'GRAY' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A010' , 'LEATHER' , 'BROWN' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A011' , 'LEATHER' , 'GRAY' , 'B' FROM DUAL
    UNION ALL
    SELECT 'A012' , 'LEATHER' , 'BROWN' , 'B' FROM DUAL
    UNION ALL
    SELECT 'A013' , 'HARD' , 'GRAY' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A014' , 'HARD' , 'BLUE' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A015' , 'HARD' , 'BROWN' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A016' , 'HARD' , 'GRAY' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A017' , 'HARD' , 'BLUE' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A018' , 'HARD' , 'BROWN' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A019' , 'HARD' , 'GRAY' , 'B' FROM DUAL
    UNION ALL
    SELECT 'A020' , 'HARD' , 'BLUE' , 'B' FROM DUAL
    UNION ALL
    SELECT 'A021' , 'HARD' , 'BROWN' , 'B' FROM DUAL
    UNION ALL
    SELECT 'A022' , 'SOFT' , 'GRAY' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A023' , 'SOFT' , 'BLUE' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A024' , 'SOFT' , 'BROWN' , 'S' FROM DUAL
    UNION ALL
    SELECT 'A025' , 'SOFT' , 'GRAY' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A026' , 'SOFT' , 'BLUE' , 'M' FROM DUAL
    UNION ALL
    SELECT 'A027' , 'SOFT' , 'BROWN' , 'M' FROM DUAL;
    
CREATE TABLE INVENTORY(
    ALBUM_ID VARCHAR2(10) NOT NULL,
    ALBUM_PRICE NUMBER(5),
    A_QUANTITY NUMBER(5)
 );
 
 ALTER TABLE INVENTORY ADD CONSTRAINT PK_ALBUM_ID_INVENTORY PRIMARY KEY (ALBUM_ID);
ALTER TABLE INVENTORY ADD CONSTRAINT FK_ALBUM_ID FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID);

INSERT INTO INVENTORY (ALBUM_ID, ALBUM_PRICE, A_QUANTITY)
    SELECT 'A001' , '15000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A002' , '15000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A003' , '15000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A004' , '20000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A005' , '20000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A006' , '20000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A007' , '25000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A008' , '25000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A009' , '35000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A010' , '35000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A011' , '50000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A012' , '50000' , '100' FROM DUAL 
    UNION ALL
    SELECT 'A013' , '20000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A014' , '20000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A015' , '20000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A016' , '30000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A017' , '30000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A018' , '30000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A019' , '40000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A020' , '40000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A021' , '40000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A022' , '10000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A023' , '10000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A024' , '10000' , '100' FROM DUAL  
    UNION ALL
    SELECT 'A025' , '15000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A026' , '15000' , '100' FROM DUAL
    UNION ALL
    SELECT 'A027' , '15000' , '100' FROM DUAL; 
    
CREATE TABLE SHIPMENTS(
    SHIPMENT_ID NUMBER(5) NOT NULL,
    ORDER_ID VARCHAR2(30) NOT NULL,
    SHIPMENT_DATE DATE,
    SHIPMENT_STATUS CHAR(1) -- R:준비 P:준비중 F:배송완료
);
ALTER TABLE SHIPMENTS ADD CONSTRAINT PK_SHIPMENT_ID PRIMARY KEY(SHIPMENT_ID);
ALTER TABLE SHIPMENTS ADD CONSTRAINT FK_ORDER_ID_S FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID);
CREATE SEQUENCE SEQ_SHIPMENTS_PK
START WITH 1
INCREMENT BY 1 
MAXVALUE 99999
NOCACHE;

CREATE TABLE REFUND(
    REFUND_ID NUMBER(3) NOT NULL,
    ORDER_ID VARCHAR2(30) NOT NULL,
    REFUND_STATUS CHAR(1) -- R:준비 F:완료
);

ALTER TABLE REFUND ADD CONSTRAINT PK_REFUND_ID PRIMARY KEY(REFUND_ID);
ALTER TABLE REFUND ADD CONSTRAINT FK_ORDER_ID_R FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID);

CREATE SEQUENCE SEQ_REFUND_PK
START WITH 1
INCREMENT BY 1 
MAXVALUE 99999
NOCACHE;
